name: After push action

on: [push]

jobs:
  after_push_action:
    runs-on: ubuntu-latest

    steps:
      - name: clone my repo
        uses: actions/checkout@v3

      - name: installation
        run: make install

      - name: run linter
        run: make lint
